# Generated by Django 4.2.1 on 2023-05-28 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
